//------------------------------------------------------------------------------
// <auto-generated>
//     Ce fichier a été généré automatiquement par Visual Studio (ResXFileCodeGenerator).
//     Toute modification manuelle sera écrasée lors de la régénération.
//     Pour ajouter ou modifier des ressources, éditer le fichier Resources.resx
//     puis régénérer ce fichier via le designer de ressources de Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karate.Properties
{
    /// <summary>
    /// Classe de ressources fortement typée générée automatiquement par Visual Studio.
    /// <para>
    /// Permet d'accéder aux ressources embarquées dans l'assembly (images, chaînes, icônes, etc.)
    /// de manière typée et avec vérification à la compilation, via le <see cref="ResourceManager"/>.
    /// </para>
    /// <remarks>
    /// Générée par <c>StronglyTypedResourceBuilder</c>. NE PAS MODIFIER MANUELLEMENT.
    /// Utiliser le Concepteur de ressources Visual Studio pour ajouter/supprimer des ressources.
    /// </remarks>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        /// Retourne l'instance <see cref="System.Resources.ResourceManager"/> mise en cache.
        /// <para>
        /// Le ResourceManager permet de charger les ressources embarquées (localisées ou non)
        /// depuis le fichier <c>Karate.Properties.Resources</c> de l'assembly courant.
        /// L'instance est créée en lazy loading (à la première demande).
        /// </para>
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    // Initialisation paresseuse : création unique du ResourceManager
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Remplace la culture du thread courant pour toutes les recherches de ressources
        /// effectuées via cette classe.
        /// <para>
        /// Utile pour forcer une langue spécifique (ex : <c>new CultureInfo("fr-FR")</c>)
        /// indépendamment de la culture système. Laisser à <c>null</c> pour utiliser la culture courante.
        /// </para>
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
    }
}
