//------------------------------------------------------------------------------
// <auto-generated>
//     Ce fichier a été généré automatiquement par Visual Studio (SettingsSingleFileGenerator).
//     Toute modification manuelle sera écrasée lors de la régénération.
//     Pour gérer les paramètres, utiliser le Concepteur de paramètres de Visual Studio
//     (double-clic sur Settings.settings dans l'Explorateur de solutions).
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karate.Properties
{
    /// <summary>
    /// Classe de paramètres d'application générée automatiquement par Visual Studio.
    /// <para>
    /// Hérite de <see cref="System.Configuration.ApplicationSettingsBase"/> pour gérer
    /// la persistance des paramètres utilisateur et d'application (lecture/écriture
    /// dans le fichier de configuration user.config).
    /// </para>
    /// <remarks>
    /// Aucun paramètre personnalisé n'est défini dans ce projet.
    /// La classe est présente car créée par défaut par Visual Studio.
    /// NE PAS MODIFIER MANUELLEMENT. Utiliser Settings.settings dans le designer.
    /// </remarks>
    /// </summary>
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        /// <summary>
        /// Instance singleton thread-safe des paramètres d'application.
        /// <para>
        /// Utilise <see cref="System.Configuration.ApplicationSettingsBase.Synchronized"/>
        /// pour garantir la sécurité des accès concurrents.
        /// </para>
        /// </summary>
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        /// <summary>
        /// Accède à l'instance par défaut (singleton) des paramètres de l'application.
        /// </summary>
        public static Settings Default
        {
            get { return defaultInstance; }
        }
    }
}
